admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

admin_logout:
    path: /admin/logout

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /{_locale}
    schemes: [%httpProtocol%]
    defaults: { _locale: en}
    requirements:
      _locale: fr|en|de

app_homepage:
    defaults: { _controller: AppBundle:Homepage:index, _locale: en }
    path: /

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /admin/translation

